### ISSUE TITLE
Just a greet

### ISSUE THREAD

**Issue by Juddd** [floft/freetron#1]
I'm very glad to find your open source project here. :) I note you have no use [*OpenCV*](https://opencv.org/). That is a image processing library.

My mother is a teacher, she have to grade 100+ exam paper every week. Since my home have  a scanner, so I want to make a programme to help to do this thing. I have finish some work already, but I meet some problem now, so I find you project here. I note your environment little complict to build. If I give you a image like empty is [this](https://i.stack.imgur.com/mOoGY.png), the mark image is [this](https://i.stack.imgur.com/e6LAG.png). Your project can help to find **which item get which answer**?

**Comment by Juddd** [comment]
Of course, sometimes the layout is horizontal, like [this](https://i.stack.imgur.com/gzPPS.png) and [this](https://i.stack.imgur.com/0JA8F.png). I'm very look forward to your reply. :)

**Comment by floft** [comment]
Yeah, when I wrote this I did it without OpenCV. It was more fun writing it from scratch, figuring out how to solve the problems on my own. If I were to do it again, I'd probably use machine learning for recognizing the filled-in bubbles and probably OpenCV too for simplicity.

My program (as is) only works on the forms linked in the README file. You could modify it to support any other format if you wanted to, but it's using a list of rules with thresholds to determine what is or isn't a filled-in bubble. Likely other approaches would be better. I googled "opencv bubble forms" and quite a few articles showed up that could be useful to you. Following those would be much easier than modifying freetron. (Note: these articles were published after I wrote this program.)
